name: .NET

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
    APP_NAME: multiframework
    DOTNET_VERSION: '3.1.x'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: 'Setup Dotnet Environment'
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1.1
      
    - name: Restore dependencies
      run: dotnet restore

    - name: 'Build with Dotnet'
      run: dotnet build --configuration Release

    - name: 'Publish Build Output'
      run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/${{ env.APP_NAME }} -f netcore3.1

    - name: 'Upload Artifacts'
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.APP_NAME }}
        path: ${{ env.DOTNET_ROOT }}/${{ env.APP_NAME }}
